[package]
name = "crypto_address_validator"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.38", features = ["cargo"] }
bs58 = "0.5.1"
sha2 = "0.10.9"
bech32 = "0.11.0"

[dev-dependencies]
pretty_assertions = "1.4.1"
